server:
  port: 8185
  address: 0.0.0.0
  ssl:
    enabled: false
spring:
  application:
    name: updates-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/updates
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    consumer:
      group-id: updates-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.value.default.type: otus_test_ms.notifications.main.consumer.ConsumerDto
        spring.json.key.default.type: java.lang.String
updates:
  kafka:
    brokers: localhost:9091,localhost:9092,localhost:9093
    topic: ms.updates.status.info
management:
  server:
    port:
      8080
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    env:
      show-values:
        always
  prometheus:
    metrics:
      export:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  config: classpath:environment/logback-spring.xml
